name: cartee
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.1
  get: ^4.6.6
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  flutter_native_splash: ^2.4.1
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.2.0+3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  lottie: ^3.1.2
  dotlottie_loader: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/cartee-logos-no-bg/
    - assets/logos/cartee-logos/
    - assets/logos/brand-logos/
    - assets/images/
    - assets/animations/delivery.json
    - assets/animations/payment.json
    - assets/animations/product.json
    - assets/animations/success.json
    - assets/animations/verify.json

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Black.ttf
          weight: 900
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/WorkSans-Thin.ttf
          weight: 100
